### ISSUE TITLE
Consider making tag templatable from certain fields

### ISSUE THREAD

**Issue by georgespalding** [georgespalding/dropwizard-fluent-appender#4]
In some cases it would be desirable to build the fluent event tag dynamically.
The perhaps most important usecase would be to be able to have the log level as the second part of the tag. An idea would be to support templating in the `tag`configured, and the templates get replaced in runtime. There should be a predefined set of template variables available (and documented) for this purpose.

Example:
```yaml
logging:
  appenders:
  - type: fluent
    host: ${FLUENTD_HOST}
    port: ${FLUENTD_PORT}
    encoder:
      type: v0
      tag: "${application-name}.${level}"
```
Which should result in the following tag being sent to fluentd in the event tag for the application MyApp when an error logging event is received: `MyApp.error`.
